---
name: CI

on: [push, pull_request]

jobs:
  tidy:
    name: Tidy
    runs-on: ubuntu-latest
    container: docker.io/library/golang:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go Tidy
        run: go mod tidy
      - name: Git Diff
        run: git diff --exit-code

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: docker.io/library/golang:${{ matrix.go }}-buster
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OS Dependencies
        run: apt-get update && apt-get install -y tar make gcc
      - name: Go Dependencies
        run: go mod vendor
      - name: Tests
        run: go test -v -cover ./...